"""Import statements tell python what packages you'll be using.

You can use 'as' to change how you refer to the package. In this file,
I import matplotlib.pyplot as plt so I don't have to type out
'matplotlib.pyplot' every time I want to use it.
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###############################################################################
"""After the import statements, I define one function: plot_with_pandas.
Function definitions start with the word 'def' and end when
the indentation ends. For example:


def ex1():
    print("This line is part of the function 'ex1' because it's indented")
    print("This line is still part of the function 'ex1'")
    print("Blank lines do not end the current level of indentation")

print("This line is not part of the function 'ex1' because it's not indented")


"""


def plot_with_pandas():
    """Generate plot, using pandas."""

    df = pd.read_csv('inputs/run_times.csv')                             # CHANGE THIS LINE TO READ FILE WITH SPEEDS, NOTJUST RUN TIMES

    df.plot(x="trial", y="distance")                                     # CHANGE THIS LINE TO PLOT TRIALS ON X-AXIS AND SPEEDS ON Y-AXIS

    plt.show(block=False)

    # ADD LABELS FOR X AND Y AXIS, ADD TITLE, ADD GRID


def generate_new_data():
    """Generate new data."""

    df = pd.read_csv('inputs/run_times.csv')

    speed = df['distance'] + df['time'] / df['trial']                    # CORRECT  THIS LINE TO CALCULATE SPEED

    temp_dictionary = {'trial' : df['trial'],
                       'distance' : df['distance'],
                       'time' : df['time'],
                       'speed' : speed}

    # then, use the dictionary to create the dataframe
    df_new = pd.DataFrame(temp_dictionary)

    # dataframes can be written to csv files directly
    df_new.to_csv("outputs/speeds.csv", index=False)

    return df_new


###############################################################################
# These next lines 'call' the functions defined above.
# If you erase the lines below (or put a # in front of them) this code won't
# 'do' anything (it won't generate a graph anymore.)

dataframe = generate_new_data()    # MAKE MODIFICATIONS IN THE FUNCTION SO THIS READS RUN_TIMES.CSV, CALCULATES SPEED, AND WRITES RESULTS TO SPEED.CSV
plot_with_pandas()                 # MAKE MODIFICATIONS IN THE FUNCTION SO THAT THIS PLOTS SPEED BY TRIAL, AND THEN IT MAKES A NICE FIGURE

# These lines print statistics of speed data - uncomment them  to see numbers printed to the screen
#print('Minimum speed is: ', end='')
#print(np.amin(dataframe['speed']))
#print('Maximum speed is: ', end='')
#print('np.amax(dataframe['speed']))
#print('Average speed is: ', end='')
#print('np.mean(dataframe['speed']))
#print('Statistics generated by pandas directly: ')
#print(dataframe.describe())

input("Press enter to close the graph (if it's still open) and end the program")
